Repository guacsec/trustify, pull requests merged in 2024-10, with the labels that each got.

#872 fix: update openapi spec
  modules/fundamental/src/sbom/endpoints/mod.rs
  openapi.yaml
Labels: bug

#890 fix: don't clear qualifiers when ingesting CSAF
  modules/fundamental/tests/advisory/csaf/reingest.rs
  modules/ingestor/src/service/advisory/csaf/creator.rs
Labels: Advisories

#895 feat: add an endpoint to get the counts of sboms per purl
  modules/fundamental/src/sbom/endpoints/mod.rs
  modules/fundamental/src/sbom/service/sbom.rs
  modules/fundamental/src/sbom/service/test.rs
  openapi.yaml
Labels: enhancement, frontend, SBOMs

#929 fix: performance issue in update_deprecated_advisory
  migration/src/lib.rs
  migration/src/m0000650_alter_advisory_tracking/update_deprecated_advisory.sql
  migration/src/m0000680_fix_update_deprecated_advisory.rs
Labels: bug, Advisories

#942 chore: Enhance testing around cyclonedx ingestion
  etc/test-data/cyclonedx/cyclonedx-circular.json
  etc/test-data/cyclonedx/loop.json
  etc/test-data/cyclonedx/simple.json
  etc/test-data/cyclonedx/simple_with_purl_dep_ref.json
  modules/analysis/src/service.rs
Labels: Vulnerability Correlation, cyclonedx
