Repository guacsec/trustify, pull requests merged in 2024-11, with the labels that each got.

#985 fix: have a default empty array
  migration/src/lib.rs
  migration/src/m0000720_alter_sbom_fix_null_array.rs
Labels: bug

#996 Add version and handle circular deps in analysis graphs
  etc/test-data/spdx/simple.json
  modules/analysis/src/endpoints.rs
  modules/analysis/src/model.rs
  modules/analysis/src/service.rs
  openapi.yaml
Labels: Vulnerability Correlation

#1027 Set implied relationships for SBOM components in analysis graph
  Cargo.lock
  entity/src/relationship.rs
  modules/analysis/Cargo.toml
  modules/analysis/src/endpoints.rs
  modules/analysis/src/model.rs
  modules/analysis/src/service.rs
  openapi.yaml
Labels: Vulnerability Correlation

#1052 feat: allow more postgres database options
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/src/config.rs
  common/src/db/mod.rs
Labels: DB
