Repository guacsec/trustify, pull requests merged in 2025-02, with the labels that each got.

#1250 fix: add index for organizations by name
  migration/src/lib.rs
  migration/src/m0000880_org_name_index.rs
Labels: bug

#1242 OpenAPI generated files are not committed to UI repository
  .github/workflows/openapi.yaml
Labels: frontend, ci

#1373 ci: have a concurrency group per branch
  .github/workflows/benchmark.yaml
  .github/workflows/latest-release.yaml
Labels: CI/CD
