Repository guacsec/trustify, pull requests merged in 2025-05, with the labels that each got.

#1598 fix: properly evaluate the UpdateSbom permission
  common/auth/src/permission.rs
Labels: backport release/0.2.z

#1600 chore: clean up labels API, add tests, handle removing, add docs
  entity/src/labels.rs
  modules/fundamental/README.md
  modules/fundamental/src/advisory/endpoints/label.rs
  modules/fundamental/src/advisory/endpoints/test.rs
  modules/fundamental/src/sbom/endpoints/label.rs
  modules/fundamental/src/sbom/endpoints/test.rs
  modules/fundamental/src/test/label.rs
  modules/fundamental/src/test/mod.rs
  modules/importer/src/runner/clearly_defined_curation/mod.rs
  modules/importer/src/runner/csaf/storage.rs
  modules/importer/src/runner/cve/mod.rs
  modules/importer/src/runner/osv/mod.rs
  modules/importer/src/runner/sbom/storage.rs
  openapi.yaml
Labels: enhancement, Advisories, SBOMs, backport release/0.2.z

#1594 reorganize query docs so openapi picks it up
  common/src/db/query.rs
  openapi.yaml
Labels: documentation, Developer experience, backport release/0.2.z

#1588 fix: ensure middleware sboms work with analysis graph and optimise graph cache
  modules/analysis/src/endpoints/tests/latest_filters.rs
  modules/analysis/src/service/load.rs
  modules/analysis/src/service/mod.rs
Labels: backport release/0.2.z

#1613 refactor: clean up more duplicate code
  modules/analysis/src/service/load.rs
Labels: backport release/0.2.z

#1629 fix: return 404 when `/weakness/foobar_id` has no results
  modules/fundamental/src/weakness/endpoints/mod.rs
  modules/fundamental/src/weakness/endpoints/test.rs
  openapi.yaml
Labels: backport release/0.2.z

#1654 docs(adr): Proposal for a "PURL report"
  docs/adrs/00007-purl-report.md
Labels: ADR
