Repository guacsec/trustify, pull requests merged in 2025-04, with the labels that each got.

#1512 fix: TC-2388 OSV range with last_affected
  etc/test-data/cyclonedx/ghsa_test.json
  etc/test-data/osv/GHSA-458h-wv48-fq75.json
  modules/fundamental/tests/sbom/details.rs
  modules/ingestor/src/service/advisory/osv/loader.rs
Labels: Vulnerability Correlation

#1510 docs: add documentation for pod's resources
  docs/book/modules/admin/nav.adoc
  docs/book/modules/admin/pages/resources.adoc
Labels: documentation

#1522 chore: remove imageindex>imagevariant custom codepath.
  etc/test-data/cyclonedx/rh/image_index_variants/example_container_index.json
  etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_amd64.json
  etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_arm64.json
  etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_ppc.json
  etc/test-data/cyclonedx/rh/image_index_variants/example_container_variant_s390x.json
  etc/test-data/cyclonedx/rh/image_index_variants/imageindex_quarkus_mandrel.json
  etc/test-data/cyclonedx/rh/image_index_variants/imagevariant_quarkus_mandrel_amd64.json
  etc/test-data/cyclonedx/rh/image_index_variants/imagevariant_quarkus_mandrel_arm64.json
  modules/analysis/src/endpoints/tests/rh_variant.rs
  modules/analysis/src/service/collector.rs
  modules/analysis/src/service/mod.rs
Labels: backport/0.2.z

#1518 chore: update otel dependencies
  Cargo.lock
  Cargo.toml
  docs/otel.md
Labels: backport/0.2.z

#1523 fix: pythonver_cmp function to properly handle local versions
  migration/src/lib.rs
  migration/src/m0001020_alter_pythonver_cmp.rs
  migration/src/m0001020_alter_pythonver_cmp_fns/pythonver_cmp_down.sql
  migration/src/m0001020_alter_pythonver_cmp_fns/pythonver_cmp_up.sql
  modules/ingestor/tests/version/pythonver.rs
Labels: backport/0.2.z

#1529 chore: update dependencies
  Cargo.lock
  Cargo.toml
  common/src/db/query/filter.rs
  common/src/db/query/value.rs
Labels: backport/0.2.z

#1528 chore: update petgraph and drop forked deepsize
  Cargo.lock
  Cargo.toml
  common/Cargo.toml
  common/src/cpe.rs
  modules/analysis/Cargo.toml
  modules/analysis/src/model.rs
Labels: backport/0.2.z

#1542 perf: TC-2428 add gin index to advisory
  migration/src/lib.rs
  migration/src/m0001030_perf_adv_gin_index.rs
  migration/src/m0001030_perf_adv_gin_index/advisory_identifier_version_document_id_title.sql
  modules/fundamental/src/advisory/service/mod.rs
Labels: performance, backport/0.2.z

#1544 fix: scale test references the PR number
  .github/workflows/scale-test.yaml
Labels: performance

#1553 fix: ensure that an invalid CVSS does not panic
  Cargo.lock
  Cargo.toml
  etc/test-data/csaf/issues/cvss_1/ssa-054046.json
  modules/ingestor/tests/issues.rs
Labels: Advisories, backport/0.2.z

#1556 fix: Python versions PLSQL comparator (TC-2469)
  migration/src/lib.rs
  migration/src/m0001040_alter_pythonver_cmp.rs
  migration/src/m0001040_alter_pythonver_cmp_fns/pythonver_cmp_down.sql
  migration/src/m0001040_alter_pythonver_cmp_fns/pythonver_cmp_up.sql
  modules/ingestor/tests/version/pythonver.rs
Labels: Vulnerability Correlation, backport/0.2.z

#1576 fix: remove advisory_vulnerability gist index
  migration/src/lib.rs
  migration/src/m0001060_advisory_vulnerability_indexes.rs
Labels: backport release/0.2.z

#1580 test: add test for lazy loading
  modules/fundamental/src/test/common.rs
  modules/fundamental/tests/analysis.rs
Labels: backport release/0.2.z

#1582 feat(analysis): log cache eviction note on info level
  modules/analysis/src/model.rs
Labels: backport release/0.2.z

#1586 perf: minor analysis graph loading optimisation
  modules/analysis/src/service/load.rs
Labels: backport release/0.2.z
