Repository guacsec/trustify, pull requests merged in 2025-06, with the labels that each got.

#1679 build: add feature flag for graphql
  Cargo.toml
  entity/Cargo.toml
  entity/src/advisory.rs
  entity/src/cvss3.rs
  entity/src/labels.rs
  entity/src/organization.rs
  entity/src/sbom.rs
  entity/src/vulnerability.rs
  modules/fundamental/Cargo.toml
  modules/fundamental/src/sbom/model/mod.rs
  modules/fundamental/src/vulnerability/model/mod.rs
  modules/graphql/Cargo.toml
  server/Cargo.toml
  server/src/openapi.rs
  server/src/profile/api.rs
  server/src/profile/importer.rs
Labels: backport release/0.3.z

#1699 task: align UI removal of Analytics prop
  Cargo.lock
  server/src/profile/api.rs
Labels: backport release/0.3.z

#1709 fix: env variable name typo
  common/src/db/embedded.rs
Labels: backport release/0.3.z

#1706 chore: Fix up API definition of /api/v2/sbom/{id}/licenseIds
  modules/fundamental/src/license/service/mod.rs
  modules/fundamental/src/sbom/endpoints/mod.rs
  modules/fundamental/src/sbom/endpoints/test.rs
  openapi.yaml
Labels: backport release/0.3.z

#1711 feat: implement validation of labels
  Cargo.lock
  entity/Cargo.toml
  entity/src/labels.rs
  modules/fundamental/src/advisory/service/mod.rs
  modules/fundamental/src/error.rs
  modules/fundamental/src/sbom/service/label.rs
  modules/fundamental/src/test/label.rs
  modules/importer/src/service.rs
  modules/ingestor/src/graph/advisory/mod.rs
  modules/ingestor/src/graph/error.rs
  modules/ingestor/src/graph/sbom/mod.rs
Labels: backport release/0.3.z, labels

#1717 fix(storage): urlencode bucket name
  Cargo.lock
  modules/storage/Cargo.toml
  modules/storage/src/service/s3.rs
Labels: backport release/0.3.z

#1716 test(importer): increase unit test coverage and refactor test helpers
  modules/importer/src/model/mod.rs
Labels: backport release/0.3.z

#1723 chore: Aligning the 404 messages
  modules/analysis/src/endpoints/mod.rs
  modules/fundamental/src/advisory/endpoints/mod.rs
  modules/fundamental/src/ai/endpoints/mod.rs
  modules/fundamental/src/organization/endpoints/mod.rs
  modules/fundamental/src/product/endpoints/mod.rs
  modules/fundamental/src/sbom/endpoints/mod.rs
  modules/fundamental/src/vulnerability/endpoints/mod.rs
  modules/fundamental/src/weakness/endpoints/mod.rs
  modules/importer/src/endpoints.rs
  modules/user/src/endpoints.rs
  openapi.yaml
Labels: backport release/0.3.z

#1732 feat(analysis): log graph cache size during startup
  modules/analysis/src/model.rs
Labels: backport release/0.3.z

#1735 Revert "ci: set non-blocking codecov status checks (#1725)"
  codecov.yml
Labels: CI/CD

#1738 test: ensure that example importers can be created
  server/src/sample_data.rs
Labels: backport release/0.3.z

#1729 fix: timeout the DB ping and return "false"
  server/src/profile/api.rs
  server/src/profile/importer.rs
  server/src/profile/mod.rs
Labels: backport release/0.3.z

#1753 feat(analysis): provide for status details
  common/src/model/bytesize.rs
  modules/analysis/README.md
  modules/analysis/src/endpoints/mod.rs
  modules/analysis/src/model.rs
  modules/analysis/src/service/load.rs
  modules/analysis/src/service/mod.rs
  modules/analysis/src/service/test.rs
  openapi.yaml
Labels: backport release/0.3.z

#1759 fix: prevent dumping massive amounts of log info
  modules/analysis/src/service/collector.rs
  modules/analysis/src/service/mod.rs
Labels: backport release/0.3.z

#1765 feat(analysis): reduce memory consumption by 10-15%
  Cargo.lock
  modules/analysis/Cargo.toml
  modules/analysis/src/model/graph.rs
  modules/analysis/src/service/collector.rs
  modules/analysis/src/service/load.rs
  modules/analysis/src/service/mod.rs
  modules/analysis/src/service/test.rs
Labels: backport release/0.3.z
